# QingCloud services configuration

qy_config:
  access_key_id: "WJJWLKWMBVUOYDTOTMPP"
  secret_access_key: "CRQeZa6bYxHc6lwnFHAiqjxTWiHq28DPsecvfIyw"
  host: "api.kunlcloud.com"
  port: 80
  protocol: "http"
  uri: "app"
  app_id: "app-ptfa3keh"

poxied_config:
  type: bi
  config:
    api_uri: "http://192.168.130.44:28080/bi/api"
    adminv: "admin"
    admin_passv: "g5"
    default_passv: "adfe2ER1wec"    #create new user
    default_group: "qingcloud"      #user group
#    redirect_uri: "http://192.168.130.44:28080/bi/Viewer?proc=1&action=viewer&db=%E9%A3%8E%E6%9C%BA%E5%81%A5%E5%BA%B7%E8%AF%84%E4%BC%B0%E5%8A%A9%E6%89%8B/%E9%A3%8E%E6%9C%BA%E5%BA%94%E7%94%A8%E5%8F%AF%E8%A7%86%E5%8C%96%E8%AE%BE%E8%AE%A1V2"
    redirect_uri: "http://192.168.130.44:28080/bi/Viewer?au_act=login"