# QingCloud services configuration

qy_config:
  access_key_id: "WJJWLKWMBVUOYDTOTMPP"
  secret_access_key: "CRQeZa6bYxHc6lwnFHAiqjxTWiHq28DPsecvfIyw"
  host: "api.kunlcloud.com"
  port: 80
  protocol: "http"
  uri: "app"
  app_id: "app-ptfa3keh"

poxied_config:
  type: bi
  config:
    uri: "http://192.168.130.44:28080/bi"
    adminv: "admin"
    admin_passv: "g5"
    default_passv: "adfe2ER1wec"
    default_group: "qingcloud"